### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by shaunakv1** [msalinas92/CacheBolt#26]
Docker Container silently fails to start. It simply exits with return code of 1

Docker Command
```
 docker run --rm -p 3000:3000 \
  -v $(pwd)/config:/config \
  -v $(pwd)/cache:/data \
  ghcr.io/msalinas92/cachebolt:latest  --config /config/config.yaml
```

Config Yaml

```yaml
# 🔧 Unique identifier for this CacheBolt instance
app_id: test-cache

# 🌐 Port to bind the main proxy server (default: 3000)
proxy_port: 3000

# 🛠️ Port to bind the admin interface and /metrics (default: 3001)
admin_port: 3001

# 🚦 Maximum number of concurrent outbound requests to the downstream service
max_concurrent_requests: 200

# 🌐 Base URL of the upstream API/backend to which requests are proxied
downstream_base_url: https://test

# 💾 Backend used for persistent cache storage
# Available options: gcs, s3, azure, local
storage_backend: local

# 🪣 Name of the Google Cloud Storage bucket (used if storage_backend is 'gcs')
#gcs_bucket: cachebolt

# 🪣 Name of the Amazon S3 bucket (used if storage_backend is 's3')
#s3_bucket: my-cachebolt-bucket

# 📦 Name of the Azure Blob Storage container (used if storage_backend is 'azure')
azure_container: cachebolt

# 🧠 Memory cache configuration
cache:
  # 🚨 System memory usage threshold (%) above which in-memory cache will start evicting entries
  memory_threshold: 80

  # 🔁 Percentage of requests (per key) that should trigger a refresh from backend instead of using cache
  # Example: 10% means 1 in every 10 requests will bypass cache
  refresh_percentage: 10

# ⚠️ Latency-based failover configuration
latency_failover:
  # ⌛ Default maximum allowed latency in milliseconds for any request
  default_max_latency_ms: 900

  # 🛣️ Path-specific latency thresholds
  # path_rules:
  #   - pattern: "^/api/v1/products/.*"
  #     max_latency_ms: 1500
  #   - pattern: "^/auth/.*"
  #     max_latency_ms: 1000

# 🚫 List of request headers to ignore when computing cache keys (case-insensitive)
ignored_headers:
  - postman-token
  - if-none-match

```
